/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wave_util_ShineWrapper */

#ifndef _Included_wave_util_ShineWrapper
#define _Included_wave_util_ShineWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     wave_util_ShineWrapper
 * Method:    getCtxBlkSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_wave_util_ShineWrapper_getCtxBlkSize
  (JNIEnv *, jclass);

/*
 * Class:     wave_util_ShineWrapper
 * Method:    init
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_wave_util_ShineWrapper_init
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     wave_util_ShineWrapper
 * Method:    fini
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_wave_util_ShineWrapper_fini
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     wave_util_ShineWrapper
 * Method:    encode
 * Signature: ([B[BI[BI)I
 */
JNIEXPORT jint JNICALL Java_wave_util_ShineWrapper_encode
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
