/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#include "types.h"
#include "ShineWrapper.h"

JNIEXPORT jint JNICALL Java_wave_util_ShineWrapper_getCtxBlkSize(JNIEnv *env, jclass cls) 
{
	return sizeof(struct shine_ctx);
}

JNIEXPORT void JNICALL Java_wave_util_ShineWrapper_init(JNIEnv *env, jobject obj, jbyteArray shine)
{
	jbyte *ctx;
	struct shine_ctx *shctx;

	ctx = (*env)->GetByteArrayElements(env, shine, NULL);
	shctx = (struct shine_ctx *)ctx;
	shine_init(shctx);
	shine_update(shctx);
	open_bit_stream(shctx, "dummy.wav");
	(*env)->ReleaseByteArrayElements(env, shine, ctx, 0);
}

JNIEXPORT jint JNICALL Java_wave_util_ShineWrapper_encode
  (JNIEnv *env, jclass cls, jbyteArray shine, jbyteArray jsrc, jint len, jbyteArray jdst, jint size)
{
	jint retval;
	jbyte *src, *dst;
	struct shine_ctx *shctx;

	src = (*env)->GetByteArrayElements(env, jsrc, NULL);
	dst = (*env)->GetByteArrayElements(env, jdst, NULL);
	shctx = (struct shine_ctx *)(*env)->GetByteArrayElements(env, shine, NULL);

	retval = shine_frame(shctx, src, len, dst, size);

	(*env)->ReleaseByteArrayElements(env, shine, (jbyte *)shctx, 0);
	(*env)->ReleaseByteArrayElements(env, jsrc, src, JNI_ABORT);
	(*env)->ReleaseByteArrayElements(env, jdst, dst, 0);
	return retval;
}

JNIEXPORT void JNICALL Java_wave_util_ShineWrapper_fini(JNIEnv *env, jclass cls, jbyteArray shine)
{
	struct shine_ctx *shctx;
	shctx = (struct shine_ctx *)(*env)->GetByteArrayElements(env, shine, NULL);
	close_bit_stream(shctx);
	shine_fini(shctx);
	(*env)->ReleaseByteArrayElements(env, shine, (jbyte *)shctx, JNI_ABORT);
}

