/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mpg123 */

#ifndef _Included_com_example_mpg123
#define _Included_com_example_mpg123
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mpg123
 * Method:    length
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_wave_util_MadPlayer_length
  (JNIEnv *, jclass);

/*
 * Class:     com_example_mpg123
 * Method:    init
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_wave_util_MadPlayer_init
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_example_mpg123
 * Method:    fini
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_wave_util_MadPlayer_fini
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_example_mpg123
 * Method:    feed
 * Signature: ([B[BII)I
 */
JNIEXPORT jint JNICALL Java_wave_util_MadPlayer_feed
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_example_mpg123
 * Method:    frame
 * Signature: ([B[BII)I
 */
JNIEXPORT jint JNICALL Java_wave_util_MadPlayer_frame
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
